language: java
jdk: openjdk17

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE shopping_bag1;" -U postgres
  - psql -c "CREATE USER shopping_bag WITH PASSWORD 'shop@123';" -U postgres

script:
  - ./mvnw clean install -B